import time

from src.heist_path.HeistPath import HeistPath


class HeistPathA(HeistPath):
    def run_path(self):
        self.goto_b1()
        self.is_in_team()
        # self.arb_bank_b1_attack()
        # self.arb_bank_goto_lg1()
        self.check_current_floor(1)
        self.sleep(0.10)
        # self.arb_bank_goto_colle()
        # self.check_current_floor(2)
        # self.sleep(0.10)
        # self.arb_bank_colle_f1_earn()
        # self.arb_bank_goto_colle_f2()
        # self.arb_bank_colle_f2_earn()
        # self.arb_bank_goto_safeexit()

    def goto_b1(self):
        self.custom_log("寻路到大厅负一层")
        self.switch_to_runner()
        self.sleep(0.81)
        self.send_key_down("w")
        self.sleep(0.32)
        self.send_key_down("lshift")
        self.sleep(0.16)
        self.send_key_up("lshift")
        self.sleep(2.68)
        self.send_key_down("d")
        self.sleep(2.55)
        self.send_key_up("d")
        self.sleep(0.37)
        self.wait_send_interac(is_lock=True)
        self.send_key_down("w")
        self.sleep(1.8)
        deadline = time.time() + 5
        while time.time() < deadline:
            self.send_key_down("space")
            self.sleep(0.06)
            self.send_key_up("space")
            self.sleep(0.26)
        if not self.wait_send_interac(key_up_sleep=0, is_lock=True):
            self.goto_b1_interrupted()
        self.send_key_down("w")
        self.sleep(0.2)
        self.send_key("lshift")
        self.sleep(0.2)
        self.send_key_down("d")
        self.sleep(0.75)
        self.send_key_up("d")
        self.sleep(0.01)
        self.send_key_down("a")
        self.sleep(0.75)
        self.send_key_up("a")
        self.sleep(0.5)
        self.send_key_up("w")
        self.sleep(0.29)
        self.send_key_down("a")
        self.sleep(0.29)
        self.send_key("lshift")
        self.sleep(4.00)
        self.send_key_up("a")
        self.sleep(0.04)
        self.send_key_down("s")
        self.sleep(0.29)
        self.send_key("lshift")
        self.sleep(1.93)
        self.send_key_up("s")
        self.sleep(0.04)
        self.send_key_down("d")
        self.sleep(0.29)
        self.send_key("lshift")
        self.sleep(2.91)
        self.send_key_up("d")
        self.sleep(0.01)
        self.send_key_down("a")
        self.sleep(0.71)
        self.send_key_up("a")
        self.sleep(0.36)
        self.send_key_down("s")
        self.sleep(1.90)
        self.send_key_up("s")
        self.sleep(0.14)
        self.send_key_down("w")
        self.sleep(3)
        self.send_key_up("w")
        self.sleep(0.13)
        self.send_key_down("s")
        self.sleep(0.14)
        self.send_key_up("s")
        self.sleep(0.47)
        self.jump_combat_once()
        self.send_key_down("f")
        self.sleep(0.5)
        self.send_key_down("w")
        self.sleep(0.22)
        self.send_key_down("lshift")
        self.sleep(0.10)
        self.send_key_up("lshift")
        self.sleep(1.5)
        self.send_key_up("f")
        self.sleep(0.1)
        self.send_key_down("d")
        self.sleep(0.1)
        self.send_key_up("w")
        self.sleep(1.5)
        self.send_key_up("d")
        self.sleep(0.35)
        self.send_key_down("a")
        self.sleep(0.88)
        self.send_key_up("a")
        self.sleep(0.30)
        self.send_key_down("s")
        self.sleep(0.43)
        self.send_key_down("lshift")
        self.sleep(0.13)
        self.send_key_up("lshift")
        self.sleep(1.4)
        self.send_key_down("a")
        self.sleep(0.53)
        self.send_key_up("a")
        self.sleep(1.64)
        self.wait_send_interac("s")
        self.sleep(0.50)
        self.send_key_down("s")
        self.sleep(0.10)
        self.wait_send_interac("s")

    def goto_b1_interrupted(self):
        self.jump_combat_once()
        self.send_key_down("w")
        self.sleep(2.02)
        self.send_key_up("w")
        self.sleep(0.51)
        self.send_key_down("s")
        self.sleep(0.60)
        self.send_key_up("s")
        self.sleep(0.22)
        self.send_key_down("d")
        self.sleep(3.41)
        self.send_key_up("d")
        self.sleep(0.32)
        self.send_key_down("a")
        self.sleep(1.16)
        self.send_key_up("a")
        self.sleep(0.20)
        self.send_key_down("w")
        self.sleep(1.51)
        self.send_key_up("w")
        self.sleep(0.11)
        self.wait_send_interac(is_lock=True)
        self.sleep(0.5)
